blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/Kentico/Home/discussions
    about: Ask questions and discuss with other community members
  - name: Kentico Github Landing page
    url: http://kentico.github.io/
    about: Explore and Join Kentico Github Community
